version: '3.8'

services:
  db:
    container_name: liveclass_db
    image: mysql:latest

    environment:
      MYSQL_DATABASE: liveclass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: liveclass
      MYSQL_PASSWORD: liveclass

    ports:
      - "3306:3306"
